### ISSUE TITLE
Tidy the project, and prepare for another release.

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/mechanize#560]
Mechanize hasn't gotten much love lately. I'm opening this issue to track some things I'd like to do, and to solicit input from the current maintainers (it's been a while since I've been involved).

Higher priority:

- [x] move to Github Actions for CI. Travis doesn't seem to be building anymore, and I'm unsure of the long-term status (#561)
- [x] get `master` green (#558, #557, #562)
- [x] generate a CVE for #547 and merge #548 to address it (similar to https://github.com/sparklemotion/nokogiri/issues/1915)
  - see https://github.com/sparklemotion/mechanize/security/advisories/GHSA-qrqm-fpv6-6r8g
- [x] cut security release v2.7.7

Lower priority:
- [ ] drop support for EOLed Rubies (< 2.5), update `required_ruby_version`
- [ ] add Rubocop's security checks to CI (which will only run after dropping support for 1.9)
- [ ] update gem dependency versions
- [ ] review current PRs for low-hanging fruit to merge
- [ ] freshen up the README
- [ ] cut release v2.8.0

Would there be objections if I spent some of my hacking time getting through this list?

**Comment by flavorjones** [comment]
OK, no comments, then I intend to proceed!

**Comment by ddoherty03** [comment]
Does it make sense to ensure the gem is compatible with Ruby3?

**Comment by flavorjones** [comment]
@ddoherty03 Without knowing what you're seeing, I can't be sure I'm answering your question. But I can say that the `master` branch now has `webrick` added as a dependency and so should work on Ruby 3 with the next release. Is that helpful? If not, can you ask a more specific question?

**Comment by flavorjones** [comment]
Release v2.7.7 has been shipped.

**Comment by flavorjones** [comment]
For the remaining items, I've created issues and a milestone:

- [drop support for EOLed Rubies (< 2.5) · Issue #563 · sparklemotion/mechanize](https://github.com/sparklemotion/mechanize/issues/563)
- [add Rubocop's security checks to CI · Issue #564 · sparklemotion/mechanize](https://github.com/sparklemotion/mechanize/issues/564)
- [update gem dependency versions · Issue #565 · sparklemotion/mechanize](https://github.com/sparklemotion/mechanize/issues/565)
- [freshen up the README · Issue #566 · sparklemotion/mechanize](https://github.com/sparklemotion/mechanize/issues/566)
- [v2.8.0 Milestone](https://github.com/sparklemotion/mechanize/milestone/7)

And I'll be flagging PRs with the milestone if I think we can easily get them in.

**Comment by flavorjones** [comment]
@ddoherty03 v2.7.7 just shipped which should support Ruby 3. If you're still experiencing problems, can you open a new issue to discuss it? Thank you!

**Comment by ddoherty03** [comment]
Yes, all good now on the Ruby3 front, for me anyway.  Thanks @flavorjones.
